2017-10-14 11:43:58 jdbc[3]: exception
java.sql.SQLClientInfoException: Client info name 'ApplicationName' not supported.
	at org.h2.jdbc.JdbcConnection.setClientInfo(JdbcConnection.java:1725)
	at com.intellij.database.remote.jdbc.impl.RemoteConnectionImpl.setClientInfo(RemoteConnectionImpl.java:461)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:346)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:683)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2017-10-14 11:44:07 jdbc[3]: exception
java.sql.SQLClientInfoException: Client info name 'ApplicationName' not supported.
	at org.h2.jdbc.JdbcConnection.setClientInfo(JdbcConnection.java:1725)
	at com.intellij.database.remote.jdbc.impl.RemoteConnectionImpl.setClientInfo(RemoteConnectionImpl.java:461)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:346)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:683)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2017-10-14 11:44:37 jdbc[3]: exception
java.sql.SQLClientInfoException: Client info name 'ApplicationName' not supported.
	at org.h2.jdbc.JdbcConnection.setClientInfo(JdbcConnection.java:1725)
	at com.intellij.database.remote.jdbc.impl.RemoteConnectionImpl.setClientInfo(RemoteConnectionImpl.java:461)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:346)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:683)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2017-10-14 11:47:26 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Tabelle "PERSON" nicht gefunden
Table "PERSON" not found; SQL statement:
select person0_.id as id1_0_, person0_.name as name2_0_ from Person person0_ [42102-192]
2017-10-14 11:47:51 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Tabelle "PERSON" nicht gefunden
Table "PERSON" not found; SQL statement:
insert into Person (id, name) values (null, ?) [42102-192]
2017-10-14 11:47:51 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Tabelle "PERSON" nicht gefunden
Table "PERSON" not found; SQL statement:
insert into Person (id, name) values (null, ?) [42102-192]
2017-10-14 11:50:58 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Tabelle "PERSON" nicht gefunden
Table "PERSON" not found; SQL statement:
select person0_.id as id1_0_, person0_.name as name2_0_ from Person person0_ [42102-192]
2017-10-14 11:51:07 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Tabelle "PERSON" nicht gefunden
Table "PERSON" not found; SQL statement:
select person0_.id as id1_0_, person0_.name as name2_0_ from Person person0_ [42102-192]
2017-10-14 11:51:09 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Tabelle "PERSON" nicht gefunden
Table "PERSON" not found; SQL statement:
insert into Person (id, name) values (null, ?) [42102-192]
2017-10-14 11:51:09 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Tabelle "PERSON" nicht gefunden
Table "PERSON" not found; SQL statement:
insert into Person (id, name) values (null, ?) [42102-192]
2017-10-14 11:59:58 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Tabelle "PERSON" nicht gefunden
Table "PERSON" not found; SQL statement:
select person0_.id as id1_0_, person0_.name as name2_0_ from Person person0_ [42102-192]
2017-10-14 12:00:03 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Tabelle "PERSON" nicht gefunden
Table "PERSON" not found; SQL statement:
select person0_.id as id1_0_, person0_.name as name2_0_ from Person person0_ [42102-192]
2017-10-14 12:00:04 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Tabelle "PERSON" nicht gefunden
Table "PERSON" not found; SQL statement:
insert into Person (id, name) values (null, ?) [42102-192]
2017-10-14 12:00:04 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Tabelle "PERSON" nicht gefunden
Table "PERSON" not found; SQL statement:
insert into Person (id, name) values (null, ?) [42102-192]
